language: node_js
node_js: node
before_script: npm install -g grunt-cli
deploy:
  provider: npm
  email: nwoltman@outlook.com
  api_key:
    secure: jTNcLjyTb0NbAU7YcSteMQZuHTXFUPge3/cyz0OAPZ0cDiQyXdr79BWJ9OvZqGpj2o95LraVtS9OM8HGBCuqKe8bFJvImMXfg+h4wuvcUEMbbK80Io0s2Pc94M+xsIURQaa8zG2BMMzZ8L/NW3JRGjJ2w7ze5YjgGlEZi6rzDGEqQvCzQINvJOWku2AI6eafVahghVt+I9ioTbQcZLxEsdM7hMXJIQ5NqFQbVbVfBM6UGTlYBYxQsnw52CrWTRy+hutGwFNWPT25gCmkk75N7Ox9kAv6nldmx5Jd125YL0jjXQFcoFB4c6o3m0mvnWLT8a1fVM9FKoDP87qfgfvidwxKue4HyKV34cwY3M7JznCddYHNWOuh+EpY5SQqE5dqOZZLTDTrHi38Ci84NzrUzHBTAtEzTEc+sGK83C1UFNPrB+WPyxt/JIX/kkt9ihaG9B6gnRVK186NYcCCyaJ9r3ymxMvMYmWHbCeEe6k3TaE2PLsBzZ8VwwQszyMztnjbuns9U4eeEag7iXLpWkhmIS62d4+vpuSE96gmOKMheNnRYjc71wseHkQPJh89LHKgRAcd0CqrKgkEhJbWe2ctQQtUOSbJo346RfQ+mjC3nMzpC2hDdpmCuTp+YevsXMvP+VxB+jejmPGHM6NXk6piVArAIvSuYpSXSAfZZ4/swLw=
  on:
    tags: true
