language: node_js
node_js: node
before_script: npm install -g grunt-cli
deploy:
  provider: npm
  email: nwoltman@outlook.com
  api_key:
    secure: MORDGHkFYyUwAm1IzkOORKULxDTfb8bupQVbB2d0QkvJ6R+mC+O0v3pOppcDmKClSetZII/yrzR0qXjXmAgNtw5HbqBW5XDxIR/7FszDO8uBMa7EGxNraLiX9oqFUM3dD9jiUWgZ35kYtblXjJmaW4sosi+f4Q0vbXImQWhM3mQ8vxPNXsAaI5h0kTNcFgGnkHSDbdabWQcXNlFmGRU4ti2LNw+Uv6/1IGCPWaIftgGahXSHDagifstclAIkzk6MEsXrUjPNbCdoKfwFHwSUwO43CgBpiIo8aG8Kqy0q97rTLH5CQoQAFd3FufHpmt33aypyiVjUpfvTRMRzgw47dCs+jmnBUB87oGBrUH88YoNau65UjbIdrI5sh0GVRCO2I1VF/aDlveTwtnBRzmpJL5IkORLZe/ucoDEjgdOdGA8p/LGRNyZhtAN7QzcDOMpBv2o4cRE5EeyFmK1yXldEBVVpVfaXoW99SlmkMEAFJqoOd8L+bK/eI8YMyLs8RzX+U4SkkymZPcybdquRC7vYHjBnU3G+dxGUfXijfhr9rRHGEL8I93WbqilatEm1FD/1zWq76OW73EAfiXqLs01pJjJ9iKMCAfARTakHL79r85JSegnUlIA7RKN36XNbYQ1SOs3FVaAHLfp+LnCz9hpBJRbHCiMX6Dw4YxXocoxz4XE=
  on:
    tags: true
